name: Test Reader

on: [push, pull_request]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.8'

      - name: Run tests
        run: |
          python -m unittest discover -s . -p 'test_reader.py'

  integration:
    runs-on: ubuntu-latest
    needs: test
    steps:
      - name: Trigger integration tests
        uses: peter-evans/repository-dispatch@v1
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          repository: <integration_repository_owner>/<integration_repository_name>
          event-type: run-integration-tests
